version: '2'
services:
  bot:
    build: .
    container_name: bot
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    environment:
        NODE_ENV: ${NODE_ENV}
        DISCORD_TOKEN: ${DISCORD_TOKEN}
        BOT_OWNER: ${BOT_OWNER}
        BOT_PREFIX: ${BOT_PREFIX}
        DB_CLIENT: ${DB_CLIENT}
        DB_USER: ${DB_USER}
        DB_DB: ${DB_NAME}
        DB_PASSWORD: ${DB_PASSWORD}
  postgres:
    container_name: db
    image: postgres:11.5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}